
export const genero  = [{value:'Clasica',label:'Clasica'},
{value:'Blues',label:'Blues'},
{value:'Jazz',label:'Jazz'},
{value:'R&B',label:'R&B'},
{value:'Rock and roll',label:'Rock and roll'},
{value:'Gospel',label:'Gospel'},
{value:'Soul',label:'Soul'},
{value:'Rock',label:'Rock'},
{value:'Metal',label:'Metal'},
{value:'Country',label:'Country'},
{value:'Funk',label:'Funk'},
{value:'Disco',label:'Disco'},
{value:'House',label:'House'},
{value:'Techno',label:'Techno'},
{value:'Pop',label:'Pop'},
{value:'Ska',label:'Ska'},
{value:'Reggae',label:'Reggae'},
{value:'Hip Hop',label:'Hip Hop'},
{value:'Drum and Bass',label:'Drum and Bass'},
{value:'Garage',label:'Garage'},
{value:'Flamenco',label:'Flamenco'},
{value:'Salsa',label:'Salsa'},
{value:'Reggaeton',label:'Reggaeton'},
{value:'Instrumental',label:'Instrumental'},
{value:'Otros',label:'Otros'}]
